# Change these first
owner: zimavi # Your GitHub organization or username, where this repository lives
repo: uptime-webs # The name of this repository

sites:
  - name: Google
    url: https://google.com

status-website:
  # baseUrl: /your-repo-name
  cname: status.zimavi.net.ua
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Up Time
  introTitle: "Up Time page for zimavi's web sites/services"
  introMessage: Here is info about status of all zimavi's web projects \n (There is no any web service, so you can check out Google)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/zimavi/uptime-webs
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
